version: "3"

services:
  redis:
    image: redis:alpine

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000 --noreload"
    depends_on:
      - redis
